### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/rails-video-review-deep-dive-into-nested-forms#2]
_Suggested Summary_
- In this video lecture, we take a detailed tour through the process of building nested forms: building the form itself using HTML and Rails helper methods, structuring our _params_ hash in a way that makes sense, and ensuring that there are writer methods on our models that receive the data from the params hash—via the controller—and instantiate objects with that data

_Suggested Objectives_
- Describe forms, params, and writer methods as a game of catch
- Use _form_for_ to have Rails generate HTML for us
- Understand what an _ActionView::Helpers::FormBuilder_ object is and what it “knows” about
- Call _#local_methods_ on a _FormBuilder_ object to see all of the methods that are available to it
- Understand that every key in the _params_ hash should correspond to a writer method
- Know what functionality we get for “free” from our association macros, and what functionality we will need to build out ourselves (with custom writers)
- Recognize that the convention is _#something_attributes=_ because there will already be a writer method for _#something=_, and we don’t want to overwrite that
- Practice building forms in HTML before using the Rails helpers, so that you can be really specific about what exactly you are creating
- Understand that the _accepts_nested_attributes_for_ macro also generates a custom writer, but is much less extensible than building that custom writer yourself
- Instantiate objects in the controller so that _fields_for_ inputs will show up in the view
- Set attributes on objects instantiated in the controller so that the form can introspect on those objects’ attributes and dynamically set labels

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback.

We have updated the materials and decided to include your suggestions in this lesson. Thank you for your contribution!

If you do not believe that this issue has been addressed, please re-open this issue. 💙
