### ISSUE TITLE
Corrupt Video 

### ISSUE THREAD

**Issue by byojelly** [learn-co-curriculum/rails-video-review-deep-dive-into-nested-forms#3]
Video stops at approximately 5:27 mark and the loading symbol appears on the video and does not go away.   I believe this is a corrupt video.

Had similar issues with the previous video lab.

**Comment by maxwellbenton** [comment]
Hi there @byojelly,

I've checked the video in this lesson but I'm having difficulty reproducing this issue, so I'm going to close it for now. The video currently plays through without failing.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
