### ISSUE TITLE
Suggested Summary

### ISSUE THREAD

**Issue by Awilmerding1** [learn-co-curriculum/rails-video-review-deep-dive-into-nested-forms#4]
This video goes through the process of creating a Rails application that stores Users, Teams and Addresses.  The video focuses on associating instances through a Nested Form.  It walks through how to create a form for a new User that has fields for adding two new addresses and fields for creating a new team OR selecting and existing team.

**Comment by maxwellbenton** [comment]
Hi @Awilmerding1,

Thank you for following through on this lesson's request!
